Improve path checking before route registration
koajs/router pull request #155
Opened 2022-06-30 14:01 UTC by peterver

## Checklist

- [x] I have ensured my pull request is not behind the main or master branch of the original repository.
- [x] I have rebased all commits where necessary so that reviewing this pull request can be done without having to merge it first.
- [x] I have written a commit message that passes commitlint linting.
- [x] I have ensured that my code changes pass linting tests.
- [x] I have ensured that my code changes pass unit tests.
- [x] I have described my pull request and the reasons for code changes along with context if necessary.

fixes: #147, #148

2022-06-30 14:07 UTC, peterver commented
@wengeezhang @etroynov kindly review once you find some time in your busy schedules

2022-06-30 15:48 UTC, etroynov commented
@3imed-jaberi @niftylettuce can you review it?

2022-06-30 15:50 UTC, etroynov requested changes

2022-06-30 15:50 UTC, etroynov commented on test/lib/router.js
> +        router.get(function (ctx, next) {});
this arguments is not necessary `(ctx, next)`

2022-06-30 16:11 UTC, peterver commented
> I also recommend you change the title, because someone may not understand that PR is about a specific issue.
> 
> It could be something like: `Improve path checking before route registration`
> 
> and add in description: `fix for issue #147` - it will link your PR with this issue
> 
> p.s thx for your help.

@etroynov should be done, I've also improved on the verb specific test by running it against all methods exported in the methods module used by the router.

2022-06-30 23:09 UTC, etroynov approved these changes

2022-07-04 06:09 UTC, SagnikPradhan approved these changes
You could probably move those checks to a function `isValidPath` instead but otherwise looks alright. 👍🏻

2022-07-04 06:26 UTC, merged

2022-07-04 12:46 UTC, peterver commented
> You could probably move those checks to a function `isValidPath` instead but otherwise looks alright. 👍🏻

@SagnikPradhan Agree :). I'll take a look either tonight or tomorrow to move those bits into utility functions, there's some other parts of the validation which could use some abstraction to ensure code readability, of course I'll write some tests for any PR I open, thanks for the tip :).